<div class="navbar-default sidebar" role="navigation">
	<div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
<li class="sidebar-search"><a class="btn btn-success btn-lg btn-block"" href="timerpt.php">Daily Time Report</button></a></li>
<li class="sidebar-search"><a class="btn btn-danger btn-lg btn-block" href="total_hours.php">Hours Worked Report</a></li>
<li class="sidebar-search"><a class="btn btn-warning btn-lg btn-block" href="audit.php">Audit Log</a></li>
		</ul>
	</div>
</div>
